Release/10.1.4
smileidentity/react-native pull request #42
Opened 2024-06-13 13:19 UTC by JNdhlovu

Story: https://app.shortcut.com/smileid/story/12503/add-offline-mode-functionality-to-v10-wrappers-react-native

## Summary
* Support for react native 0.74.x
* Android minSdkVersion 23 as per react native 0.74.x (https://reactnative.dev/blog/2024/04/22/release-0.74#android-minimum-sdk-bump-android-60)
* Added offline functionality
  * setAllowOfflineMode
  * submitJob
  * getUnsubmittedJobs
  * getSubmittedJobs
  * cleanup
* Bump android to 10.1.6 (https://github.com/smileidentity/android/releases/tag/v10.1.6)
* Bump iOS to 10.2.0 (https://github.com/smileidentity/ios/releases/tag/v10.2.0)

2024-06-13 15:17 UTC, jumaallan approved these changes

2024-06-25 23:24 UTC, vanshg requested changes

2024-06-25 23:24 UTC, vanshg commented on .github/workflows/ci.yml
> -concurrency:
Why remove the concurrency group?

2024-06-25 23:24 UTC, vanshg commented on .github/workflows/ci.yml
> +        uses: actions/checkout@v3
Why are we downgrading versions?

2024-06-25 23:24 UTC, vanshg commented on .github/workflows/ci.yml
> +        uses: actions/cache@v3
same here

2024-06-25 23:24 UTC, vanshg commented on .yarn/releases/yarn-3.6.1.cjs
Is this the entire yarn tool checked in to the repo?

2024-06-25 23:24 UTC, vanshg commented on CHANGELOG.md
> +* Support for react native 0.74.x
Are there any migration steps that will be required due to the change in architecture?

2024-06-26 23:18 UTC, vanshg approved these changes

2024-06-27 07:35 UTC, merged