feat: make ios networking methods async
smileidentity/react-native pull request #43
Opened 2024-06-15 01:31 UTC by vanshg

Story: https://app.shortcut.com/smileid/story/12926

## Summary

Updates networking methods to use asynchronous Swift code

## Known Issues

This can go in once https://github.com/smileidentity/ios/pull/183 is released

## Test Instructions

Run jobs from the RN sample app

2024-06-18 16:37 UTC, tobitech requested changes

2024-06-18 22:00 UTC, vanshg commented on ios/RNSmileID.swift
> +                resolve(["result": String(data: jsonData, encoding: .utf8)!])
Same comment here as the flutter repo -- the catch block will handle the errors. We cannot report a success if we can't convert this into a valid format for `resolve`

2024-06-19 05:17 UTC, tobitech commented on ios/RNSmileID.swift
> +                resolve(["result": String(data: jsonData, encoding: .utf8)!])
Got it.

2024-06-19 05:18 UTC, tobitech approved these changes

2024-06-20 12:36 UTC, jumaallan approved these changes

2024-06-24 09:15 UTC, merged